/** @typedef {import('./stardew-villager-types.mjs').StardewVillagerEntry} StardewVillagerEntry */

/** @type {StardewVillagerEntry[]} */
export const BACHELORS = [
  {
    slug: 'alex',
    name: 'Alex',
    role: 'Gridball Athlete',
    description: 'Trains in the town square and dreams of going pro. Responds well to hearty meals and anything that feels like a win.',
    tags: ['Marriage candidate'],
    stardew: {
      intro: 'Lives with grandparents George and Evelyn. Competitive, a little vain, and secretly worried he will not make it as an athlete.',
      villagerInfo: {
        birthday: 'Summer 13',
        livesIn: 'Pelican Town',
        address: '1 River Road',
        marriageCandidate: true,
        family: [
          { name: 'George', relation: 'grandfather' },
          { name: 'Evelyn', relation: 'grandmother' },
        ],
      },
      gifts: {
        love: ['Complete Breakfast', 'Jack Be Nimble, Jack Be Thirsty', 'Salmon Dinner', 'Stardrop Tea'],
        like: ['Egg', 'Quartz'],
        dislike: ['Clay', 'Holly'],
        hate: ['Chanterelle', 'Common Mushroom'],
      },
      heartEvents: [
        { hearts: 2, title: 'Gridball toss', summary: 'Catch the gridball in the town square when he asks for a throw.' },
        { hearts: 4, title: 'Book on the pier', summary: 'Find him reading alone at the pier — he opens up about his mom and his fears.' },
        { hearts: 5, title: 'Recipe mail', summary: 'He sends you the Salmon Dinner recipe in the mail.' },
        { hearts: 6, title: 'Cliffside talk', summary: 'Visit him on the cliff east of town; he admits he is unsure about his future.' },
        { hearts: 8, title: 'Gridball letter', summary: 'A letter invites you to his house — he asks if you think he has what it takes.' },
        { hearts: 10, title: 'Midnight gridball', summary: 'Meet him at the gridball cage after dark for a private game and a kiss.' },
      ],
      sourceUrl: 'https://stardewvalleywiki.com/Alex',
    },
    routines: [
      { label: 'Regular day', time: '8:00 AM – 5:00 PM', location: 'House → town square (training) → home' },
      { label: 'Rainy day', time: 'Morning', location: 'Stardrop Saloon (arcade)' },
      { label: 'Winter 16', time: 'All day', location: 'Night Market' },
    ],
    relationships: [
      { name: 'George & Evelyn', note: 'Raised by his grandparents; their health weighs on him more than he lets on.' },
      { name: 'Dustin & Haley', note: 'Childhood friends — you will see them around town together.' },
    ],
    trivia: ['Birthday on Summer 13 — Complete Breakfast is an easy loved gift if you have chickens and a kitchen.'],
  },
  {
    slug: 'elliott',
    name: 'Elliott',
    role: 'Writer',
    description: 'Rents a cabin on the beach and writes dramatic prose. Loves crab cakes, pomegranates, and a good metaphor.',
    tags: ['Marriage candidate'],
    stardew: {
      intro: 'The beach cabin poet of Pelican Town. Flamboyant, romantic, and always one draft away from finishing his novel.',
      villagerInfo: {
        birthday: 'Fall 5',
        livesIn: 'Pelican Town',
        address: 'Beach cabin',
        marriageCandidate: true,
      },
      gifts: {
        love: ['Crab Cakes', 'Duck Feather', 'Lobster', 'Pomegranate', 'Tom Kha Soup', 'Stardrop Tea'],
        like: ['Octopus', 'Quartz', 'Squid Ink'],
        dislike: ['Clay', 'Holly'],
        hate: ['Amaranth', 'Holly'],
      },
      heartEvents: [
        { hearts: 2, title: 'Beach reading', summary: 'Visit his cabin while he reads — he asks what you think of his latest passage.' },
        { hearts: 4, title: 'Piano at the saloon', summary: 'Find him playing piano at the Stardrop Saloon on a rainy afternoon.' },
        { hearts: 6, title: 'Rowboat confession', summary: 'He takes you rowing and reads a love poem he wrote about someone mysterious.' },
        { hearts: 8, title: 'Galaxy sword', summary: 'After you bring a Galaxy Sword, he imagines you as the hero of his next book.' },
        { hearts: 10, title: 'Beach kiss', summary: 'On a warm evening at the pier, he finally stops writing and kisses you.' },
      ],
      sourceUrl: 'https://stardewvalleywiki.com/Elliott',
    },
    routines: [
      { label: 'Regular day', time: '9:00 AM – 6:00 PM', location: 'Cabin → beach → saloon (evenings)' },
      { label: 'Rainy day', time: 'Afternoon', location: 'Stardrop Saloon' },
      { label: 'Friday', time: 'Evening', location: 'Stardrop Saloon' },
    ],
    relationships: [
      { name: 'Willy', note: 'Friendly with the fisherman — they share the beach and the saloon.' },
      { name: 'Leah', note: 'Fellow artist soul; they appreciate each other’s creative streak.' },
    ],
    trivia: ['Crab Cakes need crab, egg, flour, and oil — a solid gift once you reach the beach mines.'],
  },
  {
    slug: 'harvey',
    name: 'Harvey',
    role: 'Town Doctor',
    description: 'Runs the clinic and worries about everyone’s health — including yours after a long day in the mines.',
    tags: ['Marriage candidate'],
    stardew: {
      intro: 'Pelican Town’s doctor. Gentle, anxious, and happiest when you show up for a check-up instead of collapsing in the mines.',
      villagerInfo: {
        birthday: 'Winter 14',
        livesIn: 'Pelican Town',
        address: 'Harvey\'s Clinic',
        marriageCandidate: true,
      },
      gifts: {
        love: ['Coffee', 'Pickles', 'Super Meal', 'Truffle Oil', 'Wine', 'Stardrop Tea'],
        like: ['Chanterelle', 'Common Mushroom', 'Daffodil', 'Ginger', 'Hazelnut', 'Leek', 'Morel', 'Quartz', 'Snow Yam', 'Wild Horseradish', 'Winter Root'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Spice Berry'],
      },
      heartEvents: [
        { hearts: 2, title: 'Aerobics class', summary: 'Walk into the clinic while he leads an aerobics session with Maru and Emily.' },
        { hearts: 4, title: 'Model planes', summary: 'Visit his apartment — he shows off his radio-controlled plane collection.' },
        { hearts: 6, title: 'Balcony worry', summary: 'He spots you working too hard and lectures you about rest on the clinic balcony.' },
        { hearts: 8, title: 'Radio confession', summary: 'A late-night radio chat turns into Harvey admitting he is falling for you.' },
        { hearts: 10, title: 'Hot air balloon', summary: 'He nervously invites you on a balloon ride above the valley.' },
      ],
      sourceUrl: 'https://stardewvalleywiki.com/Harvey',
    },
    routines: [
      { label: 'Regular day', time: '8:00 AM – 4:00 PM', location: 'Clinic (counter or exam room)' },
      { label: 'Tuesday', time: 'Morning', location: 'Aerobics at clinic with Maru & Emily' },
      { label: 'Friday', time: 'Evening', location: 'Stardrop Saloon' },
    ],
    relationships: [
      { name: 'Maru', note: 'Works at the clinic as his nurse — professional and warm.' },
      { name: 'George', note: 'Regular patient; Harvey worries about his mobility.' },
    ],
    trivia: ['Coffee from the Saloon is an easy early loved gift if you are saving crops for later hearts.'],
  },
  {
    slug: 'sam',
    name: 'Sam',
    role: 'Musician',
    description: 'Skateboards around town and jams in the garage with Sebastian. Loves cactus, pizza, and anything with a good beat.',
    tags: ['Marriage candidate'],
    stardew: {
      intro: 'Jodi’s eldest, bandmate of Sebastian, and perpetual optimist. Music, skateboarding, and Joja cola fuel most of his days.',
      villagerInfo: {
        birthday: 'Summer 17',
        livesIn: 'Pelican Town',
        address: '1 Willow Lane',
        marriageCandidate: true,
        family: [
          { name: 'Jodi', relation: 'mother' },
          { name: 'Vincent', relation: 'brother' },
          { name: 'Kent', relation: 'father' },
        ],
      },
      gifts: {
        love: ['Cactus Fruit', 'Maple Bar', 'Pizza', 'Tigerseye', 'Stardrop Tea'],
        like: ['Quartz', 'Joja Cola'],
        dislike: ['Clay', 'Holly'],
        hate: ['Coal', 'Copper Ore'],
      },
      heartEvents: [
        { hearts: 2, title: 'Skateboard trick', summary: 'Watch him land a trick in the town square and cheer him on.' },
        { hearts: 4, title: 'Band practice', summary: 'Visit the Sam-Shane-Sebastian garage session behind his house.' },
        { hearts: 6, title: 'City audition', summary: 'He asks you to come to the city for an audition — your support matters.' },
        { hearts: 8, title: 'Song for you', summary: 'He plays a new track he wrote and asks how you feel about him.' },
        { hearts: 10, title: 'Boardwalk night', summary: 'A late walk on the beach ends with him kissing you under the stars.' },
      ],
      sourceUrl: 'https://stardewvalleywiki.com/Sam',
    },
    routines: [
      { label: 'Regular day', time: '9:00 AM – 8:00 PM', location: 'Home → town/skate spot → saloon (evenings)' },
      { label: 'Rainy day', time: 'Afternoon', location: 'Stardrop Saloon or home (practice)' },
      { label: 'Friday', time: 'Evening', location: 'Stardrop Saloon with bandmates' },
    ],
    relationships: [
      { name: 'Sebastian & Abigail', note: 'Close friends — arcade nights and band practice are a trio affair.' },
      { name: 'Penny', note: 'Childhood friend; they still look out for each other around town.' },
    ],
    trivia: ['Pizza is loved and buyable from the Saloon once you unlock the recipe — handy for Summer 17 birthdays.'],
  },
  {
    slug: 'sebastian',
    name: 'Sebastian',
    role: 'Programmer',
    description: 'Lives in the basement, codes by night, and rides his motorcycle when the coast is clear. Responds well to patience and thoughtful gifts.',
    tags: ['Marriage candidate'],
    stardew: {
      intro: 'Robin’s introverted stepson who works from home and escapes on his motorcycle. Warmer than he first appears — if you meet him on his schedule.',
      villagerInfo: {
        birthday: 'Winter 10',
        livesIn: 'Pelican Town',
        address: 'Mountain (Robin\'s house)',
        marriageCandidate: true,
        family: [
          { name: 'Robin', relation: 'mother' },
          { name: 'Maru', relation: 'stepsister' },
          { name: 'Demetrius', relation: 'stepfather' },
        ],
      },
      gifts: {
        love: ['Frozen Tear', 'Obsidian', 'Pumpkin Soup', 'Sashimi', 'Void Egg', 'Stardrop Tea'],
        like: ['Quartz', 'Green Frog Egg', 'Frog Egg'],
        dislike: ['Clay', 'Holly'],
        hate: ['Chanterelle', 'Common Mushroom'],
      },
      heartEvents: [
        { hearts: 2, title: 'Garage hangout', summary: 'Find him in Robin’s garage with Sam — stay for awkward small talk.' },
        { hearts: 4, title: 'Board game night', summary: 'Rainy-day invite to play Solarion Chronicles in his room.' },
        { hearts: 6, title: 'Pool at the lake', summary: 'He opens up about feeling like an outsider in his own family.' },
        { hearts: 8, title: 'Motorcycle ride', summary: 'He offers a night ride and asks if you want to leave town together someday.' },
        { hearts: 10, title: 'Obsidian gift', summary: 'Bring obsidian to the mountain after dark for a quiet confession and kiss.' },
        { hearts: 14, title: 'Frog encounter', summary: 'A rainy-day cutscene on the farm ties back to his love of frogs.' },
      ],
      sourceUrl: 'https://stardewvalleywiki.com/Sebastian',
    },
    routines: [
      { label: 'Regular day', time: '10:00 AM – 6:00 PM', location: 'Basement desk → lake (smoking) → home' },
      { label: 'Rainy day', time: 'All day', location: 'Basement (coding or games)' },
      { label: 'Friday', time: 'Evening', location: 'Stardrop Saloon with Sam' },
    ],
    relationships: [
      { name: 'Sam & Abigail', note: 'His closest friends — band practice and arcade nights.' },
      { name: 'Maru & Demetrius', note: 'Home life is tense; he keeps to the basement to avoid friction.' },
    ],
    trivia: ['Sashimi is loved and only needs any fish — Linus mails you the recipe at 3 hearts.'],
  },
  {
    slug: 'shane',
    name: 'Shane',
    role: 'Joja Clerk',
    description: 'Works at JojaMart and retreats to Marnie’s coop with his chickens. Pepper poppers and a little patience go a long way.',
    tags: ['Marriage candidate'],
    stardew: {
      intro: 'Marnie’s nephew, Jas’s guardian figure, and struggling with depression. Blunt at first, deeply loyal once you earn his trust.',
      villagerInfo: {
        birthday: 'Spring 20',
        livesIn: 'Pelican Town',
        address: 'Marnie\'s Ranch',
        marriageCandidate: true,
        family: [
          { name: 'Marnie', relation: 'aunt' },
          { name: 'Jas', relation: 'goddaughter' },
        ],
      },
      gifts: {
        love: ['Beer', 'Hot Pepper', 'Pepper Poppers', 'Pizza', 'Stardrop Tea'],
        like: ['Quartz', 'Egg'],
        dislike: ['Clay', 'Holly'],
        hate: ['Pickles', 'Wild Horseradish'],
      },
      heartEvents: [
        { hearts: 2, title: 'Coop chores', summary: 'Help him at Marnie’s chicken coop when he is in a foul mood.' },
        { hearts: 4, title: 'Cliffside cans', summary: 'Find him drinking alone on the cliff — choose words carefully.' },
        { hearts: 6, title: 'Gridball on TV', summary: 'Watch a game at the saloon; he loosens up if you share the moment.' },
        { hearts: 8, title: 'Hospital scare', summary: 'A crisis at the clinic leads to Shane admitting he needs help.' },
        { hearts: 10, title: 'Stargazing', summary: 'He invites you to the ranch at night and kisses you by the coop.' },
      ],
      sourceUrl: 'https://stardewvalleywiki.com/Shane',
    },
    routines: [
      { label: 'Regular day', time: '9:00 AM – 5:00 PM', location: 'JojaMart → ranch (evenings)' },
      { label: 'Saturday', time: 'Evening', location: 'Stardrop Saloon' },
      { label: 'Rainy day', time: 'Afternoon', location: 'Stardrop Saloon' },
    ],
    relationships: [
      { name: 'Marnie & Jas', note: 'Lives at the ranch and helps raise Jas when he is not at Joja.' },
      { name: 'Emily', note: 'Works opposite shifts at the saloon — she tries to look out for him.' },
    ],
    trivia: ['Pepper poppers need hot peppers and cheese — a cozy gift once you have a kitchen.'],
  },
];
