/** @typedef {import('../stardew-villager-types.mjs').StardewVillagerEntry} StardewVillagerEntry */

/** @type {StardewVillagerEntry[]} */
export const BACHELORETTES = [
  {
    slug: 'abigail',
    name: 'Abigail',
    role: 'Explorer & Adventurer',
    description: 'Spends rainy days in the mines and loves unusual minerals. A good friend if you enjoy combat, puzzles, and pumpkin-related gifts.',
    tags: ['Marriage candidate', 'Adventurer'],
    stardew: {
      intro: 'Lives above Pierre\'s General Store with her parents. Curious, occult-leaning, and happiest when the day involves a sword, a game, or something purple.',
      villagerInfo: {
        birthday: 'Fall 13',
        livesIn: 'Pelican Town',
        address: 'Pierre\'s General Store',
        marriageCandidate: true,
        family: [
          { name: 'Pierre', relation: 'father' },
          { name: 'Caroline', relation: 'mother' },
        ],
      },
      gifts: {
        love: ['Amethyst', 'Banana Pudding', 'Blackberry Cobbler', 'Chocolate Cake', 'Monster Compendium', 'Pumpkin', 'Pufferfish', 'Magic Rock Candy', 'Stardrop Tea'],
        like: ['Quartz', 'Ancient Sword', 'Combat Quarterly', 'Basilisk Paw', 'Bone Flute'],
        dislike: ['Sugar', 'Wild Horseradish'],
        hate: ['Clay', 'Holly'],
      },
      heartEvents: [
        { hearts: 2, title: 'Console co-op', summary: 'Help her beat a level of Journey of the Prairie King in her room at the store.' },
        { hearts: 4, title: 'Rainy duet', summary: 'Find her playing flute by the mountain lake on a rainy afternoon — she invites you to play along.' },
        { hearts: 6, title: 'Graveyard practice', summary: 'She\'s been training with a sword at night; a tense moment with Pierre leads to a quiet talk in the bushes.' },
        { hearts: 8, title: 'Spirit board', summary: 'A late visit to her room turns into an awkwardly sweet moment with her spirit board.' },
        { hearts: 10, title: 'Mines confession', summary: 'She\'s spooked in the mines and opens up about liking you as more than a friend.' },
        { hearts: 14, title: 'Backwoods rescue', summary: 'After a monster ambush in the Backwoods, she saves you — and marks the spot where it happened.' },
      ],
      sourceUrl: 'https://stardewvalleywiki.com/Abigail',
    },
    routines: [
      { label: 'Regular day', time: '9:00 AM – 8:00 PM', location: 'Room → Pierre\'s store → mountain lake (flute) → home' },
      { label: 'Rainy day', time: 'Afternoon', location: 'Store or Stardrop Saloon arcade' },
      { label: 'Wednesday', time: '10:00 AM – 10:00 PM', location: 'Museum library → graveyard → home' },
      { label: 'Friday', time: '3:00 PM – 9:00 PM', location: 'Stardrop Saloon (arcade sofa)' },
    ],
    relationships: [
      { name: 'Pierre & Caroline', note: 'Lives with her parents above the store; Caroline worries about her hobbies, and Abigail pushes back.' },
      { name: 'Sam & Sebastian', note: 'Close friends — you will often see the trio hanging out around town.' },
    ],
    trivia: [
      'After her 10-heart event, she may appear in the mines on rainy days to keep you company.',
      'Birthday gifts on Fall 13 count for extra friendship — amethyst is a safe favorite.',
    ],
  },
  {
    slug: 'emily',
    name: 'Emily',
    role: 'Salon Stylist',
    description: 'Works at the saloon and practices crystal healing on the side. Bright, creative, and happiest when you bring gems or cloth.',
    tags: ['Marriage candidate'],
    stardew: {
      intro: 'Haley\'s sister and the saloon\'s evening bartender. Spiritual, colorful, and always interpreting signs from the universe.',
      villagerInfo: {
        birthday: 'Spring 27',
        livesIn: 'Pelican Town',
        address: '2 Willow Lane',
        marriageCandidate: true,
        family: [{ name: 'Haley', relation: 'sister' }],
      },
      gifts: {
        love: ['Amethyst', 'Aquamarine', 'Cloth', 'Emerald', 'Jade', 'Ruby', 'Survival Burger', 'Wool', 'Stardrop Tea'],
        like: ['Daffodil', 'Quartz'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Fish Taco'],
      },
      heartEvents: [
        { hearts: 2, title: 'Dream visit', summary: 'Enter her house while she sleeps — you appear in her abstract dreamscape.' },
        { hearts: 4, title: 'Injured parrot', summary: 'A parrot hits her window in town; she nurses it back to health in her room.' },
        { hearts: 6, title: 'Secret dance', summary: 'She performs a private dance routine in her room — react kindly.' },
        { hearts: 8, title: 'Clothing therapy', summary: 'At the Mayor\'s Manor she hosts a group fashion session for the town.' },
        { hearts: 10, title: 'Camping in the woods', summary: 'A bear visit during a Secret Woods campout leads to a romantic night.' },
      ],
      sourceUrl: 'https://stardewvalleywiki.com/Emily',
    },
    routines: [
      { label: 'Regular day', time: '9:00 AM – 3:30 PM', location: 'Home → town errands → saloon (work)' },
      { label: 'Tuesday', time: 'Morning', location: 'Aerobics at Harvey\'s clinic' },
      { label: 'Friday', time: 'Evening', location: 'Stardrop Saloon (bar)' },
    ],
    relationships: [
      { name: 'Haley', note: 'Sisters with opposite personalities — Emily is the free spirit, Haley the perfectionist.' },
      { name: 'Gus', note: 'Employer at the Stardrop Saloon; she tends bar most evenings.' },
    ],
    trivia: ['Cloth from your loom is a reliable loved gift once you have sheep or rabbits.'],
  },
  {
    slug: 'haley',
    name: 'Haley',
    role: 'Photographer',
    description: 'Sun-loving and image-conscious at first glance. Coconut, fruit salad, and patience reveal a softer side.',
    tags: ['Marriage candidate'],
    stardew: {
      intro: 'Emily\'s younger sister and an aspiring photographer. She can seem shallow until you notice how she cares behind the camera.',
      villagerInfo: {
        birthday: 'Summer 14',
        livesIn: 'Pelican Town',
        address: '2 Willow Lane',
        marriageCandidate: true,
        family: [{ name: 'Emily', relation: 'sister' }],
      },
      gifts: {
        love: ['Coconut', 'Fruit Salad', 'Pink Cake', 'Sunflower', 'Stardrop Tea'],
        like: ['Daffodil', 'Quartz'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Wild Horseradish'],
      },
      heartEvents: [
        { hearts: 2, title: 'Lost bracelet', summary: 'Help her search the beach for a bracelet she lost in the sand.' },
        { hearts: 4, title: 'Darkroom reveal', summary: 'She shows you her photography setup at home — a side no one else sees.' },
        { hearts: 6, title: 'Cow rescue', summary: 'A cow is stuck in the fence; helping her frees it and earns real gratitude.' },
        { hearts: 8, title: 'Fair cake', summary: 'At the Stardew Valley Fair she asks you to taste her entry and shares a sweet moment.' },
        { hearts: 10, title: 'Darkroom kiss', summary: 'She develops photos of you together and kisses you in the darkroom.' },
      ],
      sourceUrl: 'https://stardewvalleywiki.com/Haley',
    },
    routines: [
      { label: 'Regular day', time: '10:00 AM – 5:00 PM', location: 'Home → town square → river (photos)' },
      { label: 'Rainy day', time: 'All day', location: 'Home (reading or photos)' },
      { label: 'Tuesday', time: 'Morning', location: 'Aerobics at clinic' },
    ],
    relationships: [
      { name: 'Emily', note: 'Older sister and roommate — they bicker but clearly depend on each other.' },
      { name: 'Alex', note: 'Childhood friend; they still hang out around the square.' },
    ],
    trivia: ['Coconut from the Desert or Ginger Island is an easy loved gift once you unlock travel.'],
  },
  {
    slug: 'leah',
    name: 'Leah',
    role: 'Sculptor',
    description: 'Moved to the valley to make art in her forest cottage. Foraged salads, goat cheese, and wild mushrooms win her over.',
    tags: ['Marriage candidate'],
    stardew: {
      intro: 'The valley\'s sculptor, living in a cabin north of town. Grounded, nature-loving, and happiest with mud on her hands.',
      villagerInfo: {
        birthday: 'Winter 23',
        livesIn: 'Cindersap Forest',
        address: 'Leah\'s Cottage',
        marriageCandidate: true,
      },
      gifts: {
        love: ['Goat Cheese', 'Poppyseed Muffin', 'Salad', 'Stir Fry', 'Stardrop Tea', 'Wine'],
        like: ['Chanterelle', 'Common Mushroom', 'Daffodil', 'Ginger', 'Hazelnut', 'Leek', 'Morel', 'Quartz', 'Snow Yam', 'Wild Horseradish', 'Winter Root'],
        dislike: ['Clay', 'Holly'],
        hate: ['Bread', 'Pancakes'],
      },
      heartEvents: [
        { hearts: 2, title: 'Forest foraging', summary: 'Meet her foraging in the woods — she talks about leaving the city for art.' },
        { hearts: 4, title: 'Saloon art show', summary: 'She displays sculptures at the saloon; show up to support her.' },
        { hearts: 6, title: 'Ex arrives', summary: 'Her old partner Kel shows up uninvited — your response shapes the scene.' },
        { hearts: 8, title: 'Sculpture invite', summary: 'She asks you to model for a piece she is carving in the rain.' },
        { hearts: 10, title: 'Cottage kiss', summary: 'Inside her cottage after finishing a sculpture, she kisses you.' },
      ],
      sourceUrl: 'https://stardewvalleywiki.com/Leah',
    },
    routines: [
      { label: 'Regular day', time: '10:00 AM – 6:00 PM', location: 'Cottage → forest → saloon (some days)' },
      { label: 'Rainy day', time: 'All day', location: 'Cottage (sculpting)' },
      { label: 'Monday', time: 'Morning', location: 'Pierre\'s (shopping)' },
    ],
    relationships: [
      { name: 'Elliott', note: 'Fellow creative on the beach — mutual respect for each other\'s work.' },
      { name: 'Evelyn', note: 'Sometimes visits George and Evelyn; gentle intergenerational friendship.' },
    ],
    trivia: ['Salad uses foraged greens from Spring — easy to gift before Winter 23 if you pick dandelions and leeks.'],
  },
  {
    slug: 'maru',
    name: 'Maru',
    role: 'Inventor & Nurse',
    description: 'Splits time between Harvey\'s clinic and gadgets in the mountain lab. Batteries, gold bars, and rare minerals impress her most.',
    tags: ['Marriage candidate'],
    stardew: {
      intro: 'Demetrius and Robin\'s daughter, Harvey\'s nurse, and tinkerer extraordinaire. Brilliant, busy, and a little competitive with Sebastian.',
      villagerInfo: {
        birthday: 'Summer 10',
        livesIn: 'Pelican Town',
        address: 'Mountain (Robin\'s house)',
        marriageCandidate: true,
        family: [
          { name: 'Robin', relation: 'mother' },
          { name: 'Demetrius', relation: 'father' },
          { name: 'Sebastian', relation: 'stepbrother' },
        ],
      },
      gifts: {
        love: ['Battery Pack', 'Cactus Fruit', 'Diamond', 'Gold Bar', 'Iridium Bar', 'Miner\'s Treat', 'Radioactive Bar', 'Rhubarb Pie', 'Strawberry', 'Stardrop Tea'],
        like: ['Quartz', 'Copper Bar', 'Iron Bar'],
        dislike: ['Clay', 'Holly'],
        hate: ['Holly', 'Salmonberry'],
      },
      heartEvents: [
        { hearts: 2, title: 'Telescope night', summary: 'Visit the mountain at night while she stargazes with her telescope.' },
        { hearts: 4, title: 'Hospital visit', summary: 'She treats a patient at the clinic and shows her competent, caring side.' },
        { hearts: 6, title: 'Gadget test', summary: 'She asks you to test a homemade device — do not flinch when it sparks.' },
        { hearts: 8, title: 'Confession on the hill', summary: 'On the mountain she admits she has been thinking about you a lot.' },
        { hearts: 10, title: 'Planetarium kiss', summary: 'Under the stars at her telescope, she kisses you.' },
      ],
      sourceUrl: 'https://stardewvalleywiki.com/Maru',
    },
    routines: [
      { label: 'Regular day', time: '8:00 AM – 4:00 PM', location: 'Clinic → home lab (evenings)' },
      { label: 'Tuesday', time: 'Morning', location: 'Aerobics at clinic' },
      { label: 'Rainy day', time: 'Afternoon', location: 'Home (inventing)' },
    ],
    relationships: [
      { name: 'Harvey', note: 'Works as his nurse — professional and fond of her boss.' },
      { name: 'Sebastian', note: 'Step-siblings who share a roof but not much overlap in daily life.' },
    ],
    trivia: ['Battery packs from lightning rods are a top-tier loved gift once your farm scales up.'],
  },
  {
    slug: 'penny',
    name: 'Penny',
    role: 'Tutor',
    description: 'Teaches Jas and Vincent and lives in the trailer with Pam. Melons, poppies, and emerald make her smile.',
    tags: ['Marriage candidate'],
    stardew: {
      intro: 'Quiet, bookish, and devoted to the town\'s kids. She dreams of a home that is not a trailer but never complains out loud.',
      villagerInfo: {
        birthday: 'Fall 2',
        livesIn: 'Pelican Town',
        address: 'Trailer (east of town)',
        marriageCandidate: true,
        family: [{ name: 'Pam', relation: 'mother' }],
      },
      gifts: {
        love: ['Diamond', 'Emerald', 'Melon', 'Poppy', 'Poppyseed Muffin', 'Sandfish', 'Tom Kha Soup', 'Stardrop Tea'],
        like: ['Quartz', 'Daffodil'],
        dislike: ['Clay', 'Holly'],
        hate: ['Beer', 'Wine'],
      },
      heartEvents: [
        { hearts: 2, title: 'Tutoring session', summary: 'Visit the trailer while she teaches Jas and Vincent — lend a hand.' },
        { hearts: 4, title: 'Library reading', summary: 'Find her in the museum library and talk about books.' },
        { hearts: 6, title: 'Bathhouse repair', summary: 'She asks for help fixing the old community bathhouse in town.' },
        { hearts: 8, title: 'Spa reopening', summary: 'The restored bathhouse opens — a tender moment in the steam.' },
        { hearts: 10, title: 'Trailer confession', summary: 'At the edge of the trailer she tells you she wants a future with you.' },
      ],
      sourceUrl: 'https://stardewvalleywiki.com/Penny',
    },
    routines: [
      { label: 'Regular day', time: '9:00 AM – 4:00 PM', location: 'Trailer → museum library (tutoring)' },
      { label: 'Tuesday', time: 'Morning', location: 'Spirits Eve prep or library' },
      { label: 'Friday', time: 'Evening', location: 'Stardrop Saloon (rare)' },
    ],
    relationships: [
      { name: 'Pam', note: 'Lives with her mother in the trailer — complicated but loving.' },
      { name: 'Jas & Vincent', note: 'Tutors both children most weekdays at the library.' },
    ],
    trivia: ['Melon in Fall is a loved gift — plant in Summer to have one ready for Fall 2 birthdays.'],
  },
];
