/** @typedef {import('../stardew-villager-types.mjs').StardewVillagerEntry} StardewVillagerEntry */

/** @type {StardewVillagerEntry[]} */
export const TOWNSFOLK = [
  {
    slug: 'caroline',
    name: 'Caroline',
    role: 'Homemaker',
    description: 'Pierre\'s wife and Abigail\'s mom. Enjoys tea in the sunroom and fresh produce from the valley.',
    tags: [],
    stardew: {
      intro: 'Runs the household above the general store and tends her sunroom tea plants. Warm but protective of her daughter.',
      villagerInfo: {
        birthday: 'Winter 7',
        livesIn: 'Pelican Town',
        address: 'Pierre\'s General Store',
        family: [
          { name: 'Pierre', relation: 'husband' },
          { name: 'Abigail', relation: 'daughter' },
        ],
      },
      gifts: {
        love: ['Fish Taco', 'Green Tea', 'Summer Spangle', 'Stardrop Tea'],
        like: ['Daffodil', 'Quartz'],
        dislike: ['Clay', 'Holly'],
        hate: ['Void Mayonnaise', 'Rabbit\'s Foot'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Caroline',
    },
    routines: [
      { label: 'Regular day', time: '9:00 AM – 3:00 PM', location: 'Store → sunroom → home' },
      { label: 'Tuesday', time: 'Morning', location: 'Aerobics at clinic' },
    ],
    relationships: [
      { name: 'Pierre & Abigail', note: 'Family above the store — Caroline worries about Abigail\'s adventurous streak.' },
      { name: 'Jodi', note: 'Friends who sometimes exercise together at the clinic.' },
    ],
    trivia: ['Green Tea comes from her sunroom plants — she may gift you a tea sapling at 2 hearts.'],
  },
  {
    slug: 'clint',
    name: 'Clint',
    role: 'Blacksmith',
    description: 'Forges tools at the smithy and harbors a crush on Emily. Gems and ore keep the conversation going.',
    tags: [],
    stardew: {
      intro: 'The town blacksmith — awkward, earnest, and shy around Emily. Upgrade your tools through him as the farm grows.',
      villagerInfo: {
        birthday: 'Winter 26',
        livesIn: 'Pelican Town',
        address: 'Blacksmith',
        occupation: 'Blacksmith',
      },
      gifts: {
        love: ['Amethyst', 'Aquamarine', 'Emerald', 'Jade', 'Omni Geode', 'Ruby', 'Topaz', 'Stardrop Tea'],
        like: ['Copper Bar', 'Gold Bar', 'Iron Bar', 'Quartz', 'Refined Quartz'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Wild Horseradish'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Clint',
    },
    routines: [
      { label: 'Regular day', time: '9:00 AM – 4:00 PM', location: 'Blacksmith' },
      { label: 'Friday', time: 'Evening', location: 'Stardrop Saloon (Emily shifts)' },
    ],
    relationships: [
      { name: 'Emily', note: 'Has a crush he cannot quite express — shows up at the saloon on her nights.' },
      { name: 'Robin', note: 'Supplies materials for farm buildings and tool upgrades.' },
    ],
    trivia: ['Any refined gem is loved — drop a topaz or aquamarine from the mines for easy friendship.'],
  },
  {
    slug: 'demetrius',
    name: 'Demetrius',
    role: 'Scientist',
    description: 'Studies the valley\'s ecosystem from the mountain lab. Strawberries and ice cream suit his analytical cheer.',
    tags: [],
    stardew: {
      intro: 'Robin\'s husband, Maru\'s father, and Sebastian\'s stepfather. Enthusiastic about science, occasionally oblivious at home.',
      villagerInfo: {
        birthday: 'Summer 19',
        livesIn: 'Pelican Town',
        address: 'Mountain (Robin\'s house)',
        family: [
          { name: 'Robin', relation: 'wife' },
          { name: 'Maru', relation: 'daughter' },
          { name: 'Sebastian', relation: 'stepson' },
        ],
      },
      gifts: {
        love: ['Ice Cream', 'Rice Pudding', 'Strawberry', 'Stardrop Tea'],
        like: ['Quartz', 'Purple Mushroom'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Holly'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Demetrius',
    },
    routines: [
      { label: 'Regular day', time: '8:00 AM – 5:00 PM', location: 'Home lab → mountain for samples' },
      { label: 'Rainy day', time: 'All day', location: 'Indoor lab' },
    ],
    relationships: [
      { name: 'Robin & Maru', note: 'Family on the mountain — he is proud of Maru\'s inventions.' },
      { name: 'Sebastian', note: 'Stepfather relationship is polite but distant.' },
    ],
    trivia: ['He may ask to study crops on your farm — say yes for a friendly boost.'],
  },
  {
    slug: 'dwarf',
    name: 'Dwarf',
    role: 'Mine Merchant',
    description: 'Hidden merchant in the mines once you understand his language. Loves gems, minerals, and mining talk.',
    tags: [],
    stardew: {
      intro: 'A mysterious figure behind a broken wall in the mines. Sells bombs, rings, and mining gear once you earn his trust.',
      villagerInfo: {
        birthday: 'Summer 22',
        livesIn: 'The Mines',
        address: 'Dwarf\'s shop (Mines)',
        occupation: 'Merchant',
      },
      gifts: {
        love: ['Amethyst', 'Aquamarine', 'Emerald', 'Jade', 'Omni Geode', 'Ruby', 'Topaz', 'Stardrop Tea'],
        like: ['Quartz', 'Earth Crystal', 'Fire Quartz', 'Frozen Tear'],
        dislike: ['Clay', 'Holly'],
        hate: ['Dwarf Scroll I', 'Dwarf Scroll II', 'Dwarf Scroll III', 'Dwarf Scroll IV'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Dwarf',
    },
    routines: [{ label: 'Always', time: 'All day', location: 'Shop in the Mines (east cavern)' }],
    relationships: [{ name: 'Wizard', note: 'Old acquaintance — the Wizard helps you learn Dwarvish.' }],
    trivia: ['Find four dwarf scrolls and donate them to unlock his shop and friendship.'],
  },
  {
    slug: 'evelyn',
    name: 'Evelyn',
    role: 'Grandmother',
    description: 'George\'s wife and Alex\'s grandmother. Bakes cookies, tends flowers, and appreciates anything sweet.',
    tags: [],
    stardew: {
      intro: 'The valley\'s kindest grandmother. She gardens, bakes, and keeps George (and Alex) grounded with warmth.',
      villagerInfo: {
        birthday: 'Winter 20',
        livesIn: 'Pelican Town',
        address: '1 River Road',
        family: [
          { name: 'George', relation: 'husband' },
          { name: 'Alex', relation: 'grandson' },
        ],
      },
      gifts: {
        love: ['Beet', 'Chocolate Cake', 'Diamond', 'Fairy Rose', 'Stuffing', 'Tulip', 'Stardrop Tea'],
        like: ['Daffodil', 'Quartz'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Wild Horseradish'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Evelyn',
    },
    routines: [
      { label: 'Regular day', time: '9:00 AM – 3:00 PM', location: 'Home → town square (garden) → home' },
      { label: 'Tuesday', time: 'Morning', location: 'Aerobics at clinic' },
    ],
    relationships: [
      { name: 'George & Alex', note: 'Keeps the household running and worries about both men in her life.' },
    ],
    trivia: ['Chocolate Cake is loved — a cozy gift if you already cook for Abigail.'],
  },
  {
    slug: 'george',
    name: 'George',
    role: 'Retiree',
    description: 'Gruff veteran who watches TV by the window. Warm up with leeks, fried mushrooms, or respectful patience.',
    tags: [],
    stardew: {
      intro: 'Evelyn\'s husband and Alex\'s grandfather. Blunt and stationary, with a soft spot he rarely shows.',
      villagerInfo: {
        birthday: 'Fall 24',
        livesIn: 'Pelican Town',
        address: '1 River Road',
        family: [
          { name: 'Evelyn', relation: 'wife' },
          { name: 'Alex', relation: 'grandson' },
        ],
      },
      gifts: {
        love: ['Fried Mushroom', 'Leek', 'Stardrop Tea'],
        like: ['Daffodil', 'Quartz'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Wild Horseradish'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/George',
    },
    routines: [{ label: 'Most days', time: 'All day', location: 'Home (chair by the window)' }],
    relationships: [
      { name: 'Evelyn', note: 'Devoted wife who handles what he cannot get up to do.' },
      { name: 'Alex', note: 'Proud of his grandson but shows it in gruff one-liners.' },
    ],
    trivia: ['Leeks forage in Spring — an easy loved gift before Fall 24.'],
  },
  {
    slug: 'gus',
    name: 'Gus',
    role: 'Saloon Owner',
    description: 'Cooks hearty meals at the Stardrop Saloon. Oranges, tropical curry, and quality ingredients keep him cheerful.',
    tags: [],
    stardew: {
      intro: 'Owner and chef of the Stardrop Saloon — the town\'s evening hub. Friendly, hard-working, and proud of his menu.',
      villagerInfo: {
        birthday: 'Summer 8',
        livesIn: 'Pelican Town',
        address: 'Stardrop Saloon',
        occupation: 'Saloon owner',
      },
      gifts: {
        love: ['Diamond', 'Escargot', 'Fish Taco', 'Orange', 'Tropical Curry', 'Stardrop Tea'],
        like: ['Quartz', 'Daffodil'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Wild Horseradish'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Gus',
    },
    routines: [{ label: 'Regular day', time: '8:00 AM – 12:00 AM', location: 'Stardrop Saloon (kitchen or bar)' }],
    relationships: [
      { name: 'Emily', note: 'Evening bartender at the saloon.' },
      { name: 'Pam', note: 'Regular at the bar — Gus knows everyone\'s usual order.' },
    ],
    trivia: ['Oranges from the Desert are a simple loved gift once the bus is running.'],
  },
  {
    slug: 'jas',
    name: 'Jas',
    role: 'Child',
    description: 'Shane and Marnie\'s goddaughter who loves fairy roses and purple things. Gentle gifts beat expensive ones.',
    tags: [],
    stardew: {
      intro: 'The quiet kid at Marnie\'s ranch. She reads, plays outside, and opens up slowly to kind neighbors.',
      villagerInfo: {
        birthday: 'Summer 4',
        livesIn: 'Pelican Town',
        address: 'Marnie\'s Ranch',
        family: [
          { name: 'Marnie', relation: 'aunt' },
          { name: 'Shane', relation: 'godfather' },
        ],
      },
      gifts: {
        love: ['Fairy Rose', 'Pink Cake', 'Plum Pudding', 'Stardrop Tea'],
        like: ['Quartz', 'Coconut'],
        dislike: ['Clay', 'Holly'],
        hate: ['Wild Horseradish', 'Triple Shot Espresso'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Jas',
    },
    routines: [
      { label: 'School days', time: '9:00 AM – 2:00 PM', location: 'Museum library with Penny' },
      { label: 'Afternoons', time: 'After school', location: 'Ranch or Cindersap Forest' },
    ],
    relationships: [
      { name: 'Vincent', note: 'Classmate and playmate — Penny tutors them together.' },
      { name: 'Shane', note: 'Godfather figure at the ranch; he tries to protect her.' },
    ],
    trivia: ['Fairy Roses bloom in Fall — plant in Summer for her Summer 4 birthday.'],
  },
  {
    slug: 'jodi',
    name: 'Jodi',
    role: 'Homemaker',
    description: 'Sam and Vincent\'s mom. Chocolate cake, crispy bass, and diamond make her busy days brighter.',
    tags: [],
    stardew: {
      intro: 'Keeps 1 Willow Lane running while Kent is away and after he returns. Overworked but endlessly caring.',
      villagerInfo: {
        birthday: 'Fall 11',
        livesIn: 'Pelican Town',
        address: '1 Willow Lane',
        family: [
          { name: 'Kent', relation: 'husband' },
          { name: 'Sam', relation: 'son' },
          { name: 'Vincent', relation: 'son' },
        ],
      },
      gifts: {
        love: ['Chocolate Cake', 'Crispy Bass', 'Diamond', 'Egg', 'Pan Fried Trout', 'Stardrop Tea'],
        like: ['Quartz', 'Daffodil'],
        dislike: ['Clay', 'Holly'],
        hate: ['Fish Taco', 'Wild Horseradish'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Jodi',
    },
    routines: [
      { label: 'Regular day', time: '9:00 AM – 3:30 PM', location: 'Home → Pierre\'s (shopping) → home' },
      { label: 'Tuesday', time: 'Morning', location: 'Aerobics at clinic' },
    ],
    relationships: [
      { name: 'Kent', note: 'Husband returning from military service in year 2 — adjustment takes time.' },
      { name: 'Caroline', note: 'Friend and fellow aerobics regular.' },
    ],
    trivia: ['Chocolate Cake works for both Jodi and Abigail — bake once, gift twice.'],
  },
  {
    slug: 'kent',
    name: 'Kent',
    role: 'Soldier',
    description: 'Returns to town in year 2 after military service. Loves fusing, super meals, and quiet understanding.',
    tags: [],
    stardew: {
      intro: 'Jodi\'s husband and Sam and Vincent\'s father. Appears from Spring Year 2 onward, adjusting to civilian life.',
      villagerInfo: {
        birthday: 'Spring 4',
        livesIn: 'Pelican Town',
        address: '1 Willow Lane',
        family: [
          { name: 'Jodi', relation: 'wife' },
          { name: 'Sam', relation: 'son' },
          { name: 'Vincent', relation: 'son' },
        ],
      },
      gifts: {
        love: ['Fiddlehead Risotto', 'Roasted Hazelnuts', 'Stardrop Tea'],
        like: ['Quartz', 'Daffodil'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Wild Horseradish'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Kent',
    },
    routines: [
      { label: 'Regular day', time: '9:00 AM – 5:00 PM', location: 'Home → town → saloon (some evenings)' },
      { label: 'Before year 2', time: '—', location: 'Away on deployment' },
    ],
    relationships: [
      { name: 'Jodi & sons', note: 'Rebuilding family rhythm after years away.' },
      { name: 'Sam', note: 'Father-son dynamic is loving but strained by what Kent experienced.' },
    ],
    trivia: ['He is not in town until Spring 1 of Year 2 — plan gifts accordingly.'],
  },
  {
    slug: 'krobus',
    name: 'Krobus',
    role: 'Shadow Merchant',
    description: 'Friendly shadow who sells rare goods in the sewers. Void eggs and diamonds feel like home.',
    tags: [],
    stardew: {
      intro: 'A shadow who prefers peace with humans. Lives in the sewers, sells unique items, and can become a roommate.',
      villagerInfo: {
        birthday: 'Winter 1',
        livesIn: 'The Sewers',
        address: 'Krobus\'s shop',
        occupation: 'Merchant',
      },
      gifts: {
        love: ['Diamond', 'Iridium Bar', 'Pumpkin', 'Void Egg', 'Wild Horseradish', 'Stardrop Tea'],
        like: ['Quartz', 'Gold Bar'],
        dislike: ['Clay', 'Holly'],
        hate: ['Bread', 'Crab Cakes'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Krobus',
    },
    routines: [{ label: 'Always', time: 'All day', location: 'Sewers shop (unlock via museum donations)' }],
    relationships: [{ name: 'Wizard', note: 'The Wizard vouches that Krobus means no harm.' }],
    trivia: ['Friendship caps at 10 hearts — he cannot receive a bouquet but can move in as a roommate.'],
  },
  {
    slug: 'leo',
    name: 'Leo',
    role: 'Island Child',
    description: 'Raised by parrots on Ginger Island until you befriend him. Duck feathers, mangoes, and patience matter most.',
    tags: [],
    stardew: {
      intro: 'A wild child on Ginger Island who joins Pelican Town after you earn his trust. Gentle, curious, and bird-loving.',
      villagerInfo: {
        birthday: 'Summer 26',
        livesIn: 'Ginger Island → Pelican Town',
        address: 'Treehouse → tent near Linus',
        occupation: 'Forager',
      },
      gifts: {
        love: ['Duck Feather', 'Mango', 'Ostrich Egg', 'Poi', 'Stardrop Tea'],
        like: ['Quartz', 'Coconut', 'Ginger'],
        dislike: ['Clay', 'Holly'],
        hate: ['Beer', 'Mead'],
      },
      heartEvents: [
        { hearts: 2, title: 'Island welcome', summary: 'First real conversation at his Ginger Island treehouse.' },
        { hearts: 4, title: 'Parrot family', summary: 'He introduces you to the birds who raised him.' },
        { hearts: 6, title: 'Moving to town', summary: 'Linus offers him a tent — Leo considers joining the valley.' },
        { hearts: 8, title: 'Town integration', summary: 'Vincent and Jas include him in play; he starts to belong.' },
        { hearts: 10, title: 'Stargazing', summary: 'A quiet night together solidifies your bond.' },
      ],
      sourceUrl: 'https://stardewvalleywiki.com/Leo',
    },
    routines: [
      { label: 'Before friendship', time: 'All day', location: 'Ginger Island (treehouse)' },
      { label: 'After moving', time: 'Daytime', location: 'Town with Linus or forest' },
    ],
    relationships: [
      { name: 'Linus', note: 'Mentor figure who helps him adjust to town life.' },
      { name: 'Jas & Vincent', note: 'First friends his age once he leaves the island.' },
    ],
    trivia: ['Unlock Ginger Island before trying to befriend him — he is not in Pelican Town at first.'],
  },
  {
    slug: 'lewis',
    name: 'Lewis',
    role: 'Mayor of Pelican Town',
    description: 'Keeps the community center project on track and hosts seasonal festivals. Loves local produce and a well-kept farm.',
    tags: [],
    stardew: {
      intro: 'Pelican Town\'s longtime mayor. Official, festival-obsessed, and secretly juggling more drama than he admits.',
      villagerInfo: {
        birthday: 'Spring 7',
        livesIn: 'Pelican Town',
        address: 'Mayor\'s Manor',
        occupation: 'Mayor',
      },
      gifts: {
        love: ['Autumn\'s Bounty', 'Glazed Yams', 'Hot Pepper', 'Purple Mushroom', 'Stardrop Tea'],
        like: ['Quartz', 'Daffodil'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Wild Horseradish'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Lewis',
    },
    routines: [
      { label: 'Regular day', time: '8:00 AM – 5:00 PM', location: 'Manor → town errands → manor' },
      { label: 'Festival days', time: 'All day', location: 'Festival grounds (hosting)' },
    ],
    relationships: [
      { name: 'Marnie', note: 'Long-running secret relationship — observant players may notice clues.' },
      { name: 'Pierre', note: 'Fellow merchant leader; they coordinate town events.' },
    ],
    trivia: ['Purple Mushrooms from the mines are a top loved gift for Spring 7 birthdays.'],
  },
  {
    slug: 'linus',
    name: 'Linus',
    role: 'Forager',
    description: 'Lives in a tent north of town and respects the valley\'s wild places. Appreciates foraged goods and kindness more than expensive gifts.',
    tags: [],
    stardew: {
      intro: 'The valley\'s gentle hermit. He forages, lives lightly, and teaches you to appreciate nature without taking too much.',
      villagerInfo: {
        birthday: 'Winter 3',
        livesIn: 'Pelican Town',
        address: 'Tent (mountain)',
        occupation: 'Forager',
      },
      gifts: {
        love: ['Blueberry Tart', 'Cactus Fruit', 'Coconut', 'Dish O\' The Sea', 'Eggplant Parmesan', 'Fried Eel', 'Honey', 'Stardrop Tea'],
        like: ['Quartz', 'Chanterelle', 'Common Mushroom'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Wild Horseradish'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Linus',
    },
    routines: [
      { label: 'Regular day', time: '9:00 AM – 6:00 PM', location: 'Tent → foraging spots → mountain lake' },
      { label: 'Rainy day', time: 'All day', location: 'Tent or bus stop shelter' },
    ],
    relationships: [
      { name: 'Leo', note: 'Takes Leo under his wing when the boy moves to the mainland.' },
      { name: 'Town', note: 'Some villagers misunderstand him; kindness from the farmer means a lot.' },
    ],
    trivia: ['He mails you the Sashimi recipe at 3 hearts — useful for Sebastian too.'],
  },
  {
    slug: 'marnie',
    name: 'Marnie',
    role: 'Rancher',
    description: 'Runs the livestock shop with Jas and Shane. Pink cake, farmer\'s lunch, and pumpkin pie feel like home.',
    tags: [],
    stardew: {
      intro: 'Owner of the ranch and animal shop east of town. Warm, practical, and tied closely to Lewis and her family.',
      villagerInfo: {
        birthday: 'Fall 18',
        livesIn: 'Pelican Town',
        address: 'Marnie\'s Ranch',
        occupation: 'Rancher',
        family: [
          { name: 'Shane', relation: 'nephew' },
          { name: 'Jas', relation: 'goddaughter' },
        ],
      },
      gifts: {
        love: ['Diamond', 'Farmer\'s Lunch', 'Pink Cake', 'Pumpkin Pie', 'Stardrop Tea'],
        like: ['Quartz', 'Egg'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Wild Horseradish'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Marnie',
    },
    routines: [
      { label: 'Regular day', time: '9:00 AM – 4:00 PM', location: 'Ranch shop → saloon (some evenings)' },
      { label: 'Monday', time: 'Closed', location: 'Ranch (not at shop counter)' },
    ],
    relationships: [
      { name: 'Lewis', note: 'Secret romance — they meet discreetly when schedules align.' },
      { name: 'Shane & Jas', note: 'Runs the household Shane and Jas depend on.' },
    ],
    trivia: ['Buy your first chicken or cow from her shop — friendship grows naturally from visits.'],
  },
  {
    slug: 'pam',
    name: 'Pam',
    role: 'Bus Driver',
    description: 'Drives the bus to the desert once repaired. Glazed yams, mead, and beer suit her straightforward taste.',
    tags: [],
    stardew: {
      intro: 'Penny\'s mother, Gus\'s regular, and the valley\'s bus driver. Rough around the edges, loyal once you respect her.',
      villagerInfo: {
        birthday: 'Spring 18',
        livesIn: 'Pelican Town',
        address: 'Trailer (east of town)',
        family: [{ name: 'Penny', relation: 'daughter' }],
        occupation: 'Bus driver',
      },
      gifts: {
        love: ['Beer', 'Cactus Fruit', 'Glazed Yams', 'Mead', 'Pale Ale', 'Parsnip Soup', 'Stardrop Tea'],
        like: ['Quartz', 'Daffodil'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Wild Horseradish'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Pam',
    },
    routines: [
      { label: 'Regular day', time: '10:00 AM – 5:00 PM', location: 'Trailer → saloon (evenings)' },
      { label: 'Bus fixed', time: 'Midday', location: 'Bus stop (Desert runs)' },
    ],
    relationships: [
      { name: 'Penny', note: 'Lives with her daughter in the trailer — tough love on both sides.' },
      { name: 'Gus', note: 'Evening regular at the Stardrop Saloon.' },
    ],
    trivia: ['Repair the community center or Joja bus to unlock Desert trips — and more time with Pam at the wheel.'],
  },
  {
    slug: 'pierre',
    name: 'Pierre',
    role: 'General Store Owner',
    description: 'Runs the town shop and competes with JojaMart prices. Loves garden-fresh produce and quiet evenings on the town square.',
    tags: [],
    stardew: {
      intro: 'Caroline\'s husband, Abigail\'s father, and merchant rival to Joja. Business-first, but devoted to his family.',
      villagerInfo: {
        birthday: 'Spring 26',
        livesIn: 'Pelican Town',
        address: 'Pierre\'s General Store',
        occupation: 'Shopkeeper',
        family: [
          { name: 'Caroline', relation: 'wife' },
          { name: 'Abigail', relation: 'daughter' },
        ],
      },
      gifts: {
        love: ['Daffodil', 'Dandelion', 'Stardrop Tea'],
        like: ['Quartz', 'Melon'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Wild Horseradish'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Pierre',
    },
    routines: [
      { label: 'Regular day', time: '9:00 AM – 5:00 PM', location: 'General Store (counter)' },
      { label: 'Wednesday', time: 'Closed', location: 'Town errands or home' },
    ],
    relationships: [
      { name: 'Caroline & Abigail', note: 'Family above the store — Pierre worries about Joja competition more than they do.' },
      { name: 'Morris', note: 'Business rival if Joja arrives in the valley.' },
    ],
    trivia: ['Daffodils forage free in Spring — an easy birthday gift on Spring 26.'],
  },
  {
    slug: 'robin',
    name: 'Robin',
    role: 'Carpenter',
    description: 'Builds farm buildings and sells house upgrades. Friendly, practical, and always ready to sketch a new coop or barn.',
    tags: [],
    stardew: {
      intro: 'The valley\'s carpenter and Demetrius\'s wife. Upgrades your farmhouse, builds barns, and keeps the mountain household running.',
      villagerInfo: {
        birthday: 'Fall 21',
        livesIn: 'Pelican Town',
        address: 'Mountain (carpenter\'s shop)',
        occupation: 'Carpenter',
        family: [
          { name: 'Demetrius', relation: 'husband' },
          { name: 'Maru', relation: 'daughter' },
          { name: 'Sebastian', relation: 'stepson' },
        ],
      },
      gifts: {
        love: ['Goat Cheese', 'Peach', 'Spaghetti', 'Stardrop Tea'],
        like: ['Quartz', 'Wood'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Wild Horseradish'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Robin',
    },
    routines: [
      { label: 'Regular day', time: '9:00 AM – 5:00 PM', location: 'Carpenter shop (counter)' },
      { label: 'Tuesday', time: 'Afternoon', location: 'Aerobics at clinic' },
    ],
    relationships: [
      { name: 'Demetrius & Maru', note: 'Family team on the mountain — Robin balances science and carpentry chaos.' },
      { name: 'Sebastian', note: 'Worries about her stepson but gives him space in the basement.' },
    ],
    trivia: ['Every farm building you order from her counter is a chance to say hello and gift spaghetti.'],
  },
  {
    slug: 'sandy',
    name: 'Sandy',
    role: 'Desert Shopkeeper',
    description: 'Runs the Oasis in Calico Desert. Cactus fruit, daffodils, and mango sweeten long desert trips.',
    tags: [],
    stardew: {
      intro: 'Your friend in the desert — cheerful, lonely, and thrilled when the bus brings visitors to her shop.',
      villagerInfo: {
        birthday: 'Fall 15',
        livesIn: 'Calico Desert',
        address: 'Oasis shop',
        occupation: 'Shopkeeper',
      },
      gifts: {
        love: ['Cactus Fruit', 'Daffodil', 'Mango', 'Stardrop Tea'],
        like: ['Quartz', 'Coconut'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Wild Horseradish'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Sandy',
    },
    routines: [{ label: 'Regular day', time: '9:00 AM – 5:00 PM', location: 'Oasis shop (Desert)' }],
    relationships: [
      { name: 'Emily', note: 'Close friend — Emily visits when the desert is open.' },
      { name: 'Pam', note: 'Pam\'s bus route is Sandy\'s lifeline to Pelican Town.' },
    ],
    trivia: ['She only appears after the bus is repaired — plan Fall 15 gifts with a desert run.'],
  },
  {
    slug: 'vincent',
    name: 'Vincent',
    role: 'Child',
    description: 'Jodi\'s younger son and Jas\'s playmate. Grapes, snails, and crayons beat fancy jewelry.',
    tags: [],
    stardew: {
      intro: 'Energetic kid who loves bugs, grapes, and heroes. Penny tutors him alongside Jas.',
      villagerInfo: {
        birthday: 'Spring 10',
        livesIn: 'Pelican Town',
        address: '1 Willow Lane',
        family: [
          { name: 'Jodi', relation: 'mother' },
          { name: 'Sam', relation: 'brother' },
          { name: 'Kent', relation: 'father' },
        ],
      },
      gifts: {
        love: ['Coconut', 'Ginger', 'Grape', 'Snail', 'Stardrop Tea'],
        like: ['Quartz', 'Daffodil'],
        dislike: ['Clay', 'Holly'],
        hate: ['Chanterelle', 'Common Mushroom'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Vincent',
    },
    routines: [
      { label: 'School days', time: '9:00 AM – 2:00 PM', location: 'Museum library with Penny' },
      { label: 'Afternoons', time: 'After school', location: 'Town or home' },
    ],
    relationships: [
      { name: 'Jas', note: 'Best friend and classmate.' },
      { name: 'Sam', note: 'Looks up to his older brother\'s skateboard tricks.' },
    ],
    trivia: ['Grapes are a loved gift and grow on summer trellises — easy for Spring 10 if planted early.'],
  },
  {
    slug: 'willy',
    name: 'Willy',
    role: 'Fisherman',
    description: 'Runs the pier shop and lives for the sea. Octopus, megalodon, and seafoam pudding hook his attention.',
    tags: [],
    stardew: {
      intro: 'Old salt on the Pelican Town pier. Sells rods and tackle, tells fish tales, and respects anyone who respects the ocean.',
      villagerInfo: {
        birthday: 'Summer 24',
        livesIn: 'Pelican Town',
        address: 'Fish Shop (beach)',
        occupation: 'Fisherman',
      },
      gifts: {
        love: ['Diamond', 'Goat Cheese', 'Mead', 'Octopus', 'Seafoam Pudding', 'Stardrop Tea'],
        like: ['Quartz', 'Sardine'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Wild Horseradish'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Willy',
    },
    routines: [{ label: 'Regular day', time: '6:00 AM – 5:00 PM', location: 'Fish Shop (beach pier)' }],
    relationships: [
      { name: 'Elliott', note: 'Beach neighbors — fishing and writing share the shoreline.' },
      { name: 'Leo', note: 'Eventually connects Leo\'s island life with the wider valley.' },
    ],
    trivia: ['He gives you your first fishing rod — returning with an octopus makes a strong early impression.'],
  },
  {
    slug: 'wizard',
    name: 'Wizard',
    role: 'Wizard',
    description: 'Reclusive mage in the tower west of town. Purple mushrooms, solar essences, and void eggs intrigue him.',
    tags: [],
    stardew: {
      intro: 'Lives in the wizard\'s tower and studies the valley\'s elemental forces. Cryptic, powerful, and key to late-game secrets.',
      villagerInfo: {
        birthday: 'Winter 17',
        livesIn: 'Pelican Town',
        address: 'Wizard\'s Tower',
        occupation: 'Wizard',
      },
      gifts: {
        love: ['Book of Stars', 'Purple Mushroom', 'Solar Essence', 'Super Cucumber', 'Void Essence', 'Stardrop Tea'],
        like: ['Quartz', 'Gold Bar'],
        dislike: ['Clay', 'Holly'],
        hate: ['Salmonberry', 'Wild Horseradish'],
      },
      sourceUrl: 'https://stardewvalleywiki.com/Wizard',
    },
    routines: [{ label: 'Regular day', time: 'All day', location: 'Wizard\'s Tower (basement or study)' }],
    relationships: [
      { name: 'Krobus & Dwarf', note: 'Mediator between shadows and dwarves — helps you translate and trade.' },
      { name: 'Caroline', note: 'Old connection hinted in community lore — the wizard knows many secrets.' },
    ],
    trivia: ['Unlock his tower by visiting after the Community Center or Joja route triggers his cutscene.'],
  },
];
